
package org.bassie.credit.application.web.services.client;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.10-b140803.1500
 * Generated source version: 2.2
 * 
 */
@WebService(name = "CustomerServices", targetNamespace = "http://services.web.customerservice.org/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface CustomerServices {


    /**
     * 
     * @param name
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "hello", targetNamespace = "http://services.web.customerservice.org/", className = "org.bassie.credit.application.web.services.client.Hello")
    @ResponseWrapper(localName = "helloResponse", targetNamespace = "http://services.web.customerservice.org/", className = "org.bassie.credit.application.web.services.client.HelloResponse")
    @Action(input = "http://services.web.customerservice.org/CustomerServices/helloRequest", output = "http://services.web.customerservice.org/CustomerServices/helloResponse")
    public String hello(
        @WebParam(name = "name", targetNamespace = "")
        String name);

    /**
     * 
     * @param createClientAccountRequest
     * @return
     *     returns org.bassie.credit.application.web.services.client.CreateClientAccountServiceResponse
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "createClientAccount", targetNamespace = "http://services.web.customerservice.org/", className = "org.bassie.credit.application.web.services.client.CreateClientAccount")
    @ResponseWrapper(localName = "createClientAccountResponse", targetNamespace = "http://services.web.customerservice.org/", className = "org.bassie.credit.application.web.services.client.CreateClientAccountResponse")
    @Action(input = "http://services.web.customerservice.org/CustomerServices/createClientAccountRequest", output = "http://services.web.customerservice.org/CustomerServices/createClientAccountResponse")
    public CreateClientAccountServiceResponse createClientAccount(
        @WebParam(name = "createClientAccountRequest", targetNamespace = "")
        CreateClientAccountRequest createClientAccountRequest);

}
