
package org.bassie.credit.application.web.services.client.loanapproval;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.10-b140803.1500
 * Generated source version: 2.2
 * 
 */
@WebService(name = "LoanApprovalServices", targetNamespace = "http://services.web.loanapproval.org/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface LoanApprovalServices {


    /**
     * 
     * @param name
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "hello", targetNamespace = "http://services.web.loanapproval.org/", className = "org.bassie.credit.application.web.services.client.loanapproval.Hello")
    @ResponseWrapper(localName = "helloResponse", targetNamespace = "http://services.web.loanapproval.org/", className = "org.bassie.credit.application.web.services.client.loanapproval.HelloResponse")
    @Action(input = "http://services.web.loanapproval.org/LoanApprovalServices/helloRequest", output = "http://services.web.loanapproval.org/LoanApprovalServices/helloResponse")
    public String hello(
        @WebParam(name = "name", targetNamespace = "")
        String name);

    /**
     * 
     * @param getLoanApprovalRequest
     * @return
     *     returns org.bassie.credit.application.web.services.client.loanapproval.LoanApprovalServiceResponse
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getLoanStatus", targetNamespace = "http://services.web.loanapproval.org/", className = "org.bassie.credit.application.web.services.client.loanapproval.GetLoanStatus")
    @ResponseWrapper(localName = "getLoanStatusResponse", targetNamespace = "http://services.web.loanapproval.org/", className = "org.bassie.credit.application.web.services.client.loanapproval.GetLoanStatusResponse")
    @Action(input = "http://services.web.loanapproval.org/LoanApprovalServices/getLoanStatusRequest", output = "http://services.web.loanapproval.org/LoanApprovalServices/getLoanStatusResponse")
    public LoanApprovalServiceResponse getLoanStatus(
        @WebParam(name = "getLoanApprovalRequest", targetNamespace = "")
        LoanApprovalRequest getLoanApprovalRequest);

}
