
package org.bassie.credit.application.web.services.client.loanapproval;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.10-b140803.1500
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "LoanApprovalServices", targetNamespace = "http://services.web.loanapproval.org/", wsdlLocation = "http://localhost:8080/LoanApprovalService/LoanApprovalServices?wsdl")
public class LoanApprovalServices_Service
    extends Service
{

    private final static URL LOANAPPROVALSERVICES_WSDL_LOCATION;
    private final static WebServiceException LOANAPPROVALSERVICES_EXCEPTION;
    private final static QName LOANAPPROVALSERVICES_QNAME = new QName("http://services.web.loanapproval.org/", "LoanApprovalServices");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:8080/LoanApprovalService/LoanApprovalServices?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        LOANAPPROVALSERVICES_WSDL_LOCATION = url;
        LOANAPPROVALSERVICES_EXCEPTION = e;
    }

    public LoanApprovalServices_Service() {
        super(__getWsdlLocation(), LOANAPPROVALSERVICES_QNAME);
    }

    public LoanApprovalServices_Service(WebServiceFeature... features) {
        super(__getWsdlLocation(), LOANAPPROVALSERVICES_QNAME, features);
    }

    public LoanApprovalServices_Service(URL wsdlLocation) {
        super(wsdlLocation, LOANAPPROVALSERVICES_QNAME);
    }

    public LoanApprovalServices_Service(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, LOANAPPROVALSERVICES_QNAME, features);
    }

    public LoanApprovalServices_Service(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public LoanApprovalServices_Service(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns LoanApprovalServices
     */
    @WebEndpoint(name = "LoanApprovalServicesPort")
    public LoanApprovalServices getLoanApprovalServicesPort() {
        return super.getPort(new QName("http://services.web.loanapproval.org/", "LoanApprovalServicesPort"), LoanApprovalServices.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns LoanApprovalServices
     */
    @WebEndpoint(name = "LoanApprovalServicesPort")
    public LoanApprovalServices getLoanApprovalServicesPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://services.web.loanapproval.org/", "LoanApprovalServicesPort"), LoanApprovalServices.class, features);
    }

    private static URL __getWsdlLocation() {
        if (LOANAPPROVALSERVICES_EXCEPTION!= null) {
            throw LOANAPPROVALSERVICES_EXCEPTION;
        }
        return LOANAPPROVALSERVICES_WSDL_LOCATION;
    }

}
